services:
  event-messenger:
    container_name: event-messenger
    image: event-messenger:latest
    build: .
    ports:
      - "8080:8080"
    volumes:
      # Persist submissions and event data
      - ./data:/app/data
    env_file:
      - .env
    environment:
      - TZ=America/Los_Angeles # Set your timezone
      - GO_ENV=production
      - DEBUG=true
    restart: unless-stopped
